services:
  chat_ui:
    build:
      context: .
      dockerfile: apps/chat_ui/Dockerfile
    ports:
      - 8501:8501
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps/chat_ui/src:/app/apps/chat_ui/src
    environment:
      - HOME=/tmp
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    networks:
      - nuvex-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps/api/src:/app/apps/api/src
    networks:
      - nuvex-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
    networks:
      - nuvex-network

networks:
  nuvex-network:
    driver: bridge